# Generated by Django 3.1.4 on 2020-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='This is an auto generated product description.', max_length=3000),
        ),
    ]
