# Generated by Django 3.1.4 on 2020-12-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201208_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-date_created']},
        ),
    ]
