# Generated by Django 3.1.4 on 2020-12-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201216_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingadd',
            name='post_code',
            field=models.CharField(default='12343', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingadd',
            name='post_code',
            field=models.CharField(default='1234', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingadd',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
