# Generated by Django 3.1.4 on 2020-12-17 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201217_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
            },
        ),
        migrations.AlterField(
            model_name='billingadd',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shippingadd',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderdetail'),
        ),
    ]
