# Generated by Django 3.1.4 on 2020-12-17 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_auto_20201217_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='payment',
            field=models.CharField(choices=[('PS', 'Paystack'), ('PP', 'PayPal')], default='PP', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
