# Generated by Django 3.1.4 on 2020-12-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201217_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingadd',
            options={'ordering': ['-id'], 'verbose_name': 'Billling Address', 'verbose_name_plural': 'Billing Addresses'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['-id'], 'verbose_name': 'Order Detail', 'verbose_name_plural': 'Order Details'},
        ),
        migrations.AlterModelOptions(
            name='shippingadd',
            options={'ordering': ['-id'], 'verbose_name': 'Shipping Address', 'verbose_name_plural': 'shipping Addresses'},
        ),
    ]
