# Generated by Django 3.1.4 on 2020-12-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='...', max_length=50),
        ),
    ]
