# Generated by Django 3.1.4 on 2020-12-18 22:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20201218_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='joined',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 12, 18, 22, 27, 38, 859477, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
