# Generated by Django 3.1.4 on 2020-12-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20201219_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
