# Generated by Django 3.1.4 on 2020-12-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20201219_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingadd',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
